version: '3.4'

services:
  person.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  
  personmicroservicesdb:
    container_name:  personmicroservicesdb
    environment:
      SA_PASSWORD: "micro12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
     - "1432:1433"