version: '3.4'

services:
  person.api:
    image: ${DOCKER_REGISTRY-}personapi
    build:
      context: .
      dockerfile: Services/Person/Person.API/Dockerfile

  personmicroservicedb:
    image: mcr.microsoft.com/mssql/server:2017-latest
