version: '3.4'

services:
  personmicroservicesdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  addressDB:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  person.api:
    image: ${DOCKER_REGISTRY-}personapi
    build:
      context: .
      dockerfile: Services/Person/Person.API/Dockerfile

  address.api:
    image: ${DOCKER_REGISTRY-}addressapi
    build:
      context: .
      dockerfile: Services/Address/Address.api/Dockerfile

volumes:
  portainer_data:



