version: '3.4'

services:
  personmicroservicesdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  portainer:
    image: portainer/portainer-ce

  person.api:
    image: ${DOCKER_REGISTRY-}personapi
    build:
      context: .
      dockerfile: Services/Person/Person.API/Dockerfile


volumes:
  portainer_data:
