version: '3.4'

services:
  personmicroservicesdb:
    container_name:  personmicroservicesdb
    environment:
      SA_PASSWORD: "Micro12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
     - "1434:1433"

  addressDB:
    container_name: addressDB
    restart: always
    ports:
     - "6379:6379"   

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:80"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  person.api:
    container_name: person.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PersonMicroServicesConnectionString=Server=personmicroservicesdb;Database=PersonMicroservicesDb;User Id=sa;Password=Micro12345678;"
    depends_on:
      - personmicroservicesdb
    ports:
      - "8000:80"
 
  address.api:
    container_name: address.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=addressDB:6379"
    depends_on:
      - addressDB
    ports:
      - "8001:80"